apiVersion: v1
kind: Service
metadata:
  name: myapp-backend
spec:
  selector:
    app: myapp-backend
  ports:
    - port: {{ .Values.environment.backendPort }}
      targetPort: {{ .Values.environment.backendPort }}
