apiVersion: v1
kind: Service
metadata:
  name: myapp-frontend
spec:
  type: NodePort
  selector:
    app: myapp-frontend
  ports:
    - port: {{ .Values.environment.frontendPort }}
      targetPort: {{ .Values.environment.frontendPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
