frontend:
  image:
    repository: ghcr.io/pnataliaa/frontend
    tag: "latest"
  replicas: 1
  service:
    nodePort: 30080

backend:
  image:
    repository: ghcr.io/pnataliaa/backend
    tag: "latest"
  replicas: 1

database:
  image:
    repository: postgres
    tag: "15"
  replicas: 1

environment:
  frontendPort: 8000
  backendPort: 5000
  databasePort: 5432
